version: "3.7"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - net

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: "ghcr.io/joeferner/redis-commander:latest"
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - net

  neo4j:
    image: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: 'neo4j/administrator'
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,apoc.load.*'
    networks:
      - net

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "db"
      #MONGO_INITDB_ROOT_USERNAME: "root"
      #MONGO_INITDB_ROOT_PASSWORD: "myBigDevPassword!"

    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net

volumes:
  ollama_data:
    driver: local
  mongo_data:
    driver: local

networks:
  net:
    driver: bridge